### ISSUE TITLE
Details of dropout?

### ISSUE THREAD

**Issue by deklanw** [JimLiu96/DeosciRec#3]
Hello,

I'm trying to reimplement your algorithm in PyTorch but I'm having trouble understanding a couple details.

The paper says,

> We also randomly dropout partial edges to prevent oversmoothing.

What's a partial edge? Looking through the code I'm seeing `node_dropout`. Is that related?

Googling I found this paper https://arxiv.org/abs/1907.10903 *DropEdge: Towards Deep Graph Convolutional Networks on Node Classification* which seems to be related?

I didn't see any ablation in the paper about the dropout. Is it significant for performance?

Also, why do you use Xavier initialization for the LA weights? Isn't that type of initialization usually used for NN layer weights?

**Comment by JimLiu96** [comment]
Thanks for your questions. Yes, the node_dropout is related to the edge dropping. It randomly drops the neighbor nodes before aggregating their embeddings. It does affect performance. But since it is not relevant to our research goal, we apply the same dropping ratio for all models with adj matrix. 

Thanks for your suggestion! We didn't analyze the effects of different initialization. It will be great if you can share the results with different initializations.

**Comment by deklanw** [comment]
Thanks for the quick reply.

Do you have a reference for this dropout strategy that I can read (theory, etc)?

Checking if I understand you correctly: in every minibatch you randomly drop out some nodes (those dropped-out nodes stayed dropped-out for all the layers in that minibatch). This is equivalent to masking out some elements of the adjacency matrix. You therefore have to recalculate the normalized adjacency, cross-hop matrix, normalized cross-hop matrix, and sum of the normalized adjacency and normalized cross-hop matrices every minibatch. That correct?

What dropout probability did you use by default?

**Comment by JimLiu96** [comment]
Actually we don't recalculate the adj. Just need to mask some entries. You can check the code [DGCF_osci.py line 164](https://github.com/JimLiu96/DeosciRec/blob/b3575da96908d062fcf23a0d4fd5f3e3f082573d/DGCF_osci.py#L164). The default is 0.1.

**Comment by deklanw** [comment]
Ah, I see. `A_fold_hat` corresponds to this matrix  ![image](https://user-images.githubusercontent.com/11601778/102625224-28d27f80-4113-11eb-94db-9f0f92715278.png)?

So, you're just dropping out from this matrix in every minibatch?

**Comment by JimLiu96** [comment]
Yes. It works the same way as in Drop-edge.

**Comment by deklanw** [comment]
I see. Thanks!
